sqlservers:
  server1:
    server: localhost
    port: 1433
    username: SA
    password: root
    sync_mode: "hybrid"
    check_new_databases: true
    skip_databases:
      - Emc_migrationTest2
 
  # server2:
  #   server: KVM-Arch\SQLEXPRESS
  #   username: Bcp
  #   password: Bcp@123
  #   sync_mode: "hybrid"  # 'full', 'incremental', or 'hybrid'
  #   check_new_databases: true  # Discover new databases
  #   skip_databases:  # Optional - if empty, migrate ALL user databases
  #     - Aquarius_12Mar2025_Final
  #     - Emc_migrationTest2
  #     - Emc_migrationTest3
  #     - Emc_migrationTest4
  #     - Emc_migrationTest5
  #     - Emc_migrationTest6
  #     - Emc_migrationTest7

postgresql:
  host: localhost
  port: 5432
  database: CompanyDB
  username: migration_user
  password: StrongPassword123
  schema: CompanyDB